export const allWords = [
  "react", "nextjs", "typescript", "developer", "keyboard", "speed",
  "frontend", "backend", "docker", "database", "api", "tailwind", "performance",
  "coding", "javascript", "github", "openai", "prisma", "server", "client",
  "function", "variable", "component", "router", "middleware", "express",
  "logic", "debug", "compile", "deploy", "testing", "virtual", "node", "framework",
  "render", "optimize", "commit", "branch", "socket", "cache", "query", "mutation",
  "design", "interface", "state", "context", "hook", "promise", "async", "await", "syntax",
  "session", "authentication", "authorization", "token", "encryption",
  "json", "rest", "graphql", "endpoint", "schema",
  "build", "bundle", "vite", "webpack", "babel", "eslint",
  "lint", "format", "debugger", "runtime", "thread", "memory",
  "processor", "event", "listener", "handler", "queue", "stack", "heap",
  "algorithm", "array", "object", "loop", "condition", "recursion",
  "class", "constructor", "inheritance", "polymorphism", "encapsulation",
  "module", "import", "export", "package", "dependency", "version",
  "pipeline", "ci", "cd", "workflow", "branching", "merge", "pullrequest",
  "container", "volume", "network", "proxy", "reverseproxy",
  "nginx", "loadbalancer", "microservice", "scalability", "availability",
  "monitoring", "logging", "metrics", "uptime", "latency",
  "cloud", "aws", "gcp", "azure", "vercel", "render",
  "dns", "domain", "ssl", "certificate", "security",
  "csrf", "cors", "request", "response", "header", "body", "params",
  "websocket", "stream", "eventsource", "worker", "threadpool",
  "postgres", "mongodb", "mysql", "sqlite", "redis",
  "index", "transaction", "querybuilder", "migration", "model",
  "zod", "validator", "controller", "service", "repository",
  "ui", "ux", "responsive", "accessibility", "animation", "transition",
  "shadow", "gradient", "theme", "color", "layout", "grid", "flexbox",
  "html", "css", "jsx", "tsx", "markdown", "editor",
  "effect", "ref", "provider", "reducer",
  "useState", "useEffect", "useMemo", "useCallback", "useRef",
  "signal", "dom", "virtualdom", "hydration", "ssr", "csr", "isr",
  "lazyload", "prefetch", "invalidate",
  "ai", "ml", "neural", "model", "dataset", "training", "inference",
  "prompt", "embedding", "vector", "tokenizer", "transformer",
  "bash", "shell", "script", "command", "terminal", "process",
  "port", "ip", "protocol", "tcp", "udp",
  "eventloop", "callback", "microtask", "macrotask",
  "storage", "localstorage", "sessionstorage", "cookie",
  "fetch", "axios", "jest", "vitest", "mock", "stub", "spy", "assert", "expect",
  "time", "date", "format", "parse", "locale",
  "canvas", "svg", "webgl", "threejs",
  "redux", "zustand", "jotai", "recoil",
  "firebase", "supabase", "trpc", "hono", "drizzle",
  "pnpm", "npm", "yarn", "workspace", "monorepo",
  "env", "dotenv", "config", "log", "error", "exception",
  "try", "catch", "throw", "finally",
];
